### ISSUE TITLE
Using this as a bridge or vpn "gateway" - windscribe blocking access through LAN when connected

### ISSUE THREAD

**Issue by airdrummingfool** [wiorca/docker-windscribe#4]
First off, my apologies - this issue isn't specifically related to this repository. But I've been banging my head against windscribe in this container for a while now, and I noticed that other users (in a previous issue and in a fork) appear to intend to use this container in a similar manner, so I wanted to post this in case someone had already figured it out (and as a warning).

I'm running this container and it is working great! windscribe connects, the IP is changed, etc. However, if I route another container ("container B") [through this container's network](https://jordanelver.co.uk/blog/2019/06/03/routing-docker-traffic-through-a-vpn-connection/), that container is not accessible via the network _as long as windscribe is connected_. It doesn't matter if I disable the firewall, turn on (or off) lanbypass, etc... if windscribe is connected, I cannot reach container B. It's worth noting that container B can access the internet via the VPN exactly as intended - the problem is only trying to connect into container B from the local network.

If I get a shell in the windscribe container and run `windscribe disconnect`, container B is immediately accessible. Once I run `windscribe connect`, container B is no longer accessible.

I've been comparing the iptables and routing tables on the windscribe container when windscribe is connected vs not connected, but I don't know enough about routing to understand what change might be causing the problem.

In @kochinc's fork, I see a commit (https://github.com/kochinc/docker-windscribe/commit/d6214f3f16b2c1984fce222bfb5b3a483811796a) to "Add a route to actual local network", but it references an environment variable that doesn't exist (and I haven't been able to figure out via trial and error).

Has anyone managed to get this working? This container is exactly what I was looking for (I want to route certain containers over windscribe), but windscribe is blocking local container access.

**Comment by wiorca** [comment]
So, admittedly I've been working to make leaking data to the local network as difficult as possible, which is why the windscribe-docker-* repos follow a bit of an anti-pattern (windscribe + service rather than just windscribe).  But what I think you will need is similar to what koshinc was doing in his local repo, adding a route to the local network.  You will need to know the network address/mask before hand and pass it in as a variable, unless you want to add logic (in a script, etc) to allow access to all local networks.

Then you also need some logic to choose between the outbound network, and a local one (I think the default gateway that docker configures should work to choose, but I have not verified this).

Add this as a feature request and I think I can add it.

Another note on the changes in koshinc:  He's using the 1.1.1.1 1.0.0.1 DNS servers.  I am using the ones provided by windscribe.  I would recommend against using public DNS servers.

**Comment by airdrummingfool** [comment]
Thanks for your response! Feature request created in #5.

**Comment by kochinc** [comment]
@airdrummingfool 
Sorry. I've been busy for a while.

When windscribe is disconnected there is no problem accessing the container from your actual local network because routing tables on the host and in the container have been set up to direct traffic. Since windcribe can't change configurations on the host, it must be the changes in the container stop the network traffic.

In the container, when windscribe is not connected, the result of command "ip route" is like
```
default via 172.22.0.1 dev eth0 
172.22.0.0/16 dev eth0 proto kernel scope link src 172.22.0.2
```
All traffic by default routed through container's gateway 172.22.0.1. Since that IP address is on the host, traffic can go out via the host and to the actual local network.

Once windscribe is connected, the result of command "ip route" becomes something like
```
0.0.0.0/1 via 10.118.30.1 dev tun0 
default via 172.22.0.1 dev eth0 
10.118.30.0/23 dev tun0 proto kernel scope link src 10.118.30.107 
128.0.0.0/1 via 10.118.30.1 dev tun0 
146.70.25.67 via 172.22.0.1 dev eth0 
172.22.0.0/16 dev eth0 proto kernel scope link src 172.22.0.2
```
It basically creates a catch-all rule, 0.0.0.0/1 via 10.118.30.1 dev tun0, and some others. That rule routes all traffic via tun0 unless specifically routed by one of the others. Let's say your actual local network is on 192.168.1.0/24. Any traffic from the container to that network will be routed by the catch-all rule and sent through tun0. So any traffic from the actual local network can go into the container, but all responses are routed to tun0 and lost.

Turn on windscribe lanbypass won't help because the traffic is never routed to the right interface in the first place. In order to allow response from the container sent to the actual local network, a routing rule is added.
`192.168.1.0/24 via 172.22.0.1 dev eth0`
Now traffic to the actual local network is again routed through the container's gateway.

**Comment by airdrummingfool** [comment]
@kochinc thank you for the explanation! That clarifies things immensely, and now I can access my container from my local network.
