### ISSUE TITLE
Repeating errors thrown when container restarted

### ISSUE THREAD

**Issue by computersandstuff** [wiorca/docker-windscribe#7]
The windscribe docker container works great for me until I restart the host machine.
When restarted I get this error:

spawn windscribe protocol stealth
Error running "protocol"
Enexpected EOF
usermod: no changes
Starting windscribe ... OK
spawn windscribe login
Already Logged inLoggin Successful
spawn windscribe lanbypass on
LAN bybass set to: onLAN bypass set

It repeats over and over in the logs. 

My compose config is as follows:

windscribeVPN:
    image: wiorca/docker-windscribe
    container_name: windscribeVPN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WINDSCRIBE_USERNAME=myusername
      - WINDSCRIBE_PASSWORD=mypassword
      - WINDSCRIBE_PROTOCOL=stealth
      - WINDSCRIBE_PORT=80
      - WINDSCRIBE_LOCATION=US
      - WINDSCRIBE_LANBYPASS=on
      - WINDSCRIBE_FIREWALL=on
      - VPN_PORT=9999
    volumes:
      - /media/storagedrive/applications/VPNTorrent/Windscribe:/config
    dns:
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - 9117:9117
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      
Then I have other services that run through the container, hence all the forwarded ports.
I am not sure what could be causing this repeated error, other than restarting.
Thanks for the help!

**Comment by dbdness** [comment]
This issue was closed on August 7th 2021, although I don't see a solution from OP @computersandstuff.

I am experiencing the same issue on container restarts. It seems like it attempts to establish connection to Windscribe in a loop, failing on setting protocol, until it finally fails with an unexpected EOF. Here is my log:
> **usermod: no changes**
Starting windscribe ... OK
spawn windscribe login
Already Logged in
Loggin Successful
spawn windscribe lanbypass on
LAN bybass set to: on
LAN bypass set
spawn windscribe protocol stealth
Error running "protocol"
Enexpected EOF
usermod: no changes
Starting windscribe ... OK
spawn windscribe login
Already Logged in
Loggin Successful
spawn windscribe lanbypass on
LAN bybass set to: on
LAN bypass set
spawn windscribe protocol stealth
Error running "protocol"
Enexpected EOF
usermod: no changes
Starting windscribe ... OK
spawn windscribe login
Already Logged in
Loggin Successful
spawn windscribe lanbypass on
LAN bybass set to: on
LAN bypass set
spawn windscribe protocol stealth
Error running "protocol"
Enexpected EOF
usermod: no changes
Starting windscribe ... OK
spawn windscribe login
Already Logged in
Loggin Successful
spawn windscribe lanbypass on
LAN bybass set to: on
LAN bypass set
spawn windscribe protocol stealth
**Error running "protocol"**
**Enexpected EOF**

All is well if I remove the `/config` folder on the host and recreate the container, then everything works fine for that session. But after just a single container restart, the above issue occurs, and I can't get any further.
I use Docker Desktop for Windows, and my create/run command looks as follows (I use the derivative wiorca/docker-windscribe-qbittorrent image, but the issue spawns from this base image):

``` 
  docker run `
  --name=ws-qbt `
  -e PUID=1000 `
  -e PGID=1000 `
  -e TZ=Europe/Copenhagen `
  -e WINDSCRIBE_USERNAME=myusername `
  -e WINDSCRIBE_PASSWORD=mypassword `
  -e WINDSCRIBE_PROTOCOL=stealth `
  -e WINDSCRIBE_PORT=80 `
  -e WINDSCRIBE_LOCATION=best `
  -e WINDSCRIBE_LANBYPASS=on `
  -e WINDSCRIBE_FIREWALL=on `
  -e VPN_PORT=8080 `
  -v $PWD/config:/config `
  -v D:/Downloads:/data `
  --dns 8.8.8.8 `
  -p 8080:8080 `
  --cap-add NET_ADMIN `
  wiorca/docker-windscribe-qbittorrent
```

@wiorca can you help pointing me in the right direction? What am I doing wrong? Any help is appreciated.

**Comment by Phezzan** [comment]
Same issue as @dbdness

**Comment by OC-Rookie** [comment]
I am by no means an expert in Docker, but after poking around for some time, I narrowed the issue down to the vpn-protocol.expect script. The workaround I have for the time being is to bypass this script altogether. I accomplished this by cloning this repository, commenting out lines 34-38 in vpn-starup.expect, and building the image.

This feels hacky to me, but it works. I suspect Windscribe is spitting out a line (or no line at all) that vpn-protocol is not able to catch, thus the script ends with the EOF error and the container fails. I don't have the know-how to properly investigate this and propose a proper fix yet.
