### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by camdnd** [wiorca/docker-windscribe#8]
Hello, I don't know if get the guide for using it. I just clone it and run ```docker-compose build``` and the ```docker-compose up``` which gave me the output
```
Recreating docker-windscribe ... done
Attaching to docker-windscribe
docker-windscribe | Starting windscribe ... OK
docker-windscribe | spawn windscribe login
docker-windscribe | Windscribe Username: CivilCrabPlayer
docker-windscribe | Windscribe Password: 
docker-windscribe | Error running "login"
docker-windscribe | Unexpected EOF
docker-windscribe exited with code 5
```

I already changed username and password but aside from that i didn't change anything else, could you please help me

**Comment by GiovanH** [comment]
Same issue here.

**Comment by GiovanH** [comment]
The error is caused by the very old version of windscribe used here. This needs to be updated to use the latest cli.

**Comment by dskrad** [comment]
Windscribe-cli version is 1.4, which according to vendor is EOL. It is the last non-alpha/beta version. 

I contacted support because I had issues logging in, but issues resolved once I used correct username and password. The support person informed me that windscribe-cli is still functional, however it will no longer be updated.

Linux GUI app v2.3.15 (Beta) is the latest linux version. I have not used this on my system. Hopefully it has a CLI option so it can be used in headless systems like docker or raspberry pi.

**Comment by builder555** [comment]
since using GUI isn't an option in this docker container, how do we get around this error with CLI? is there a new version?

**Comment by wiorca** [comment]
So at that point it'll need to be migrated over to native wireguard/openvpn-based  configuration.  I don't think it's feasible to containerize the GUI client (though I do use it at home and love it).  For now I'm happy enough with the way this works, but I am keeping it in the back of my mind that I'll need to migrate it.
